---
- hosts: local
  connection: local
  gather_facts: true
  become: true
  vars:
    key_name: eng74-jamie-aws-key
    region: eu-west-1
    image: ami-0dc8d444ee2a42d8a
    id: "Newer Ansible EC2"
    sec_group: sg-02ba23947a7c8d0f5
    subnet_id: subnet-00ac052b1e40c0164
    # ansible_python_interpreter: /urs/bin/python3

  tasks:
    - name: Installing dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python-pip
        state: present

    - name: Installing pip dependencies
      pip:
        name:
          - boto
          - boto3
          - nose
          - tornado
          - awscli
        state: present
 
    - name: get instance facts
      ec2_instance_facts:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
      register: result

    - name: create ec2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        assign_public_ip: true
        key_name: "{{ key_name }}"
        id: "{{ id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ sec_group }}"
        image: "{{ image }}"
        instance_type: t2.micro
        region: "{{ region }}"
        wait: true
        count: 1
        instance_tags: 
          Name: eng74-jamie-ansible-ec2-new

  tags: ['never', 'create_ec2']
