# This is going to be our playbook to provision the environment to run the db

# Your YAML file starts after three dashes (---)

---
# This targets db_server

- hosts: db_server
# used to define where this playbook will run

  gather_facts: yes
# gathers facts/state of machine before running the playbook
  become: true
# become is used as the root permissions to perform tasks

  tasks:
    - name: Import public key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=D68FA50FEA312927 state=present

    - name: Adding the MongoDB repository
      apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" state=present

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install mongodb
      apt:
        name: mongodb
        state: present
        update_cache: yes

    - name: unmasking mongod
      become: yes
      become_user: root
      shell: systemctl unmask mongod

    - name: start and enable mongodb
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: edit mongod config file
      become: yes
      become_user: root
      shell: sed -i 's/127.0.0.1/0.0.0.0/g' mongod.conf
      args:
        chdir: /etc

